export const pandits = [
  {
    id: "pandit-1",
    slug: "acharya-pawan-shastri",
    name: "Acharya Pawan Shastri",
    image: "/images/pandits/pawan-shastri.jpg",
    languages: ["Hindi", "Sanskrit", "English"],
    experienceYears: 14,
    city: "Noida",
    bookingsCount: 1280,
    rating: 4.9,
    onlinePuja: true,
    faceToFacePuja: true,
    gender: "Male",
    age: 42,
    hometown: "Mathura, Uttar Pradesh",
    address: "Sector 62, Noida, Uttar Pradesh",
    templeAvailability: "Weekdays and weekends by prior booking",
    callNumber: "+91-98710-12345",
    bio: "Specialist in Griha Pravesh, Rudrabhishek and Satyanarayan rituals with clear mantra guidance and devotee-focused sankalp support."
  },
  {
    id: "pandit-2",
    slug: "pandit-laxmi-narayan-upadhyay",
    name: "Pandit Laxmi Narayan Upadhyay",
    image: "/images/pandits/laxmi-narayan-upadhyay.jpg",
    languages: ["Hindi", "Marathi", "Sanskrit"],
    experienceYears: 18,
    city: "Delhi",
    bookingsCount: 1642,
    rating: 4.8,
    onlinePuja: true,
    faceToFacePuja: true,
    gender: "Male",
    age: 49,
    hometown: "Varanasi, Uttar Pradesh",
    address: "Dwarka, New Delhi",
    templeAvailability: "Morning and evening slots available",
    callNumber: "+91-98711-22345",
    bio: "Known for marriage rituals and sanskar pujas with authentic Vedic process and disciplined muhurat timing."
  },
  {
    id: "pandit-3",
    slug: "pandit-rajesh-tiwari",
    name: "Pandit Rajesh Tiwari",
    image: "/images/pandits/rajesh-tiwari.jpg",
    languages: ["Hindi", "Gujarati", "English"],
    experienceYears: 9,
    city: "Jaipur",
    bookingsCount: 940,
    rating: 4.7,
    onlinePuja: true,
    faceToFacePuja: true,
    gender: "Male",
    age: 37,
    hometown: "Jaipur, Rajasthan",
    address: "Vaishali Nagar, Jaipur",
    templeAvailability: "Available for temple and home bookings",
    callNumber: "+91-98712-32345",
    bio: "Performs Navagraha Shanti and Lakshmi puja with practical guidance for families and business owners."
  },
  {
    id: "pandit-4",
    slug: "acharya-devendra-mishra",
    name: "Acharya Devendra Mishra",
    image: "/images/pandits/devendra-mishra.jpg",
    languages: ["Hindi", "Bengali", "Sanskrit"],
    experienceYears: 16,
    city: "Varanasi",
    bookingsCount: 1525,
    rating: 4.9,
    onlinePuja: true,
    faceToFacePuja: false,
    gender: "Male",
    age: 46,
    hometown: "Varanasi, Uttar Pradesh",
    address: "Lanka, Varanasi",
    templeAvailability: "Available mostly for online sankalp sessions",
    callNumber: "+91-98713-42345",
    bio: "Experienced in Pitru karmas and dosha nivaran rituals with detailed sankalp and post-puja guidance."
  },
  {
    id: "pandit-5",
    slug: "pandit-om-prakash-sharma",
    name: "Pandit Om Prakash Sharma",
    image: "/images/pandits/om-prakash-sharma.jpg",
    languages: ["Hindi", "English", "Sanskrit"],
    experienceYears: 11,
    city: "Delhi",
    bookingsCount: 1103,
    rating: 4.6,
    onlinePuja: false,
    faceToFacePuja: true,
    gender: "Male",
    age: 41,
    hometown: "Aligarh, Uttar Pradesh",
    address: "Rohini, Delhi",
    templeAvailability: "Face to face puja with prior confirmation",
    callNumber: "+91-98714-52345",
    bio: "Popular for vastu-related rituals, Bhoomi puja and office opening ceremonies with complete samagri checklists."
  },
  {
    id: "pandit-6",
    slug: "acharya-harinarayan-joshi",
    name: "Acharya Harinarayan Joshi",
    image: "/images/pandits/harinarayan-joshi.jpg",
    languages: ["Hindi", "Gujarati", "Sanskrit"],
    experienceYears: 21,
    city: "Mathura",
    bookingsCount: 1890,
    rating: 4.9,
    onlinePuja: true,
    faceToFacePuja: true,
    gender: "Male",
    age: 54,
    hometown: "Mathura, Uttar Pradesh",
    address: "Vrindavan Road, Mathura",
    templeAvailability: "Daily temple slots available",
    callNumber: "+91-98715-62345",
    bio: "Senior acharya focused on Janmashtami, Radha Krishna puja and festival rituals with traditional sampradaya method."
  },
  {
    id: "pandit-7",
    slug: "pandit-vishal-pathak",
    name: "Pandit Vishal Pathak",
    image: "/images/pandits/vishal-pathak.jpg",
    languages: ["Hindi", "Telugu", "English"],
    experienceYears: 7,
    city: "Noida",
    bookingsCount: 780,
    rating: 4.5,
    onlinePuja: true,
    faceToFacePuja: false,
    gender: "Male",
    age: 33,
    hometown: "Prayagraj, Uttar Pradesh",
    address: "Noida Extension, Uttar Pradesh",
    templeAvailability: "Online puja slots in evening",
    callNumber: "+91-98716-72345",
    bio: "Young Vedic pandit offering online-friendly sankalp sessions, astrology-inspired remedies and quick booking response."
  },
  {
    id: "pandit-8",
    slug: "acharya-ramesh-tripathi",
    name: "Acharya Ramesh Tripathi",
    image: "/images/pandits/ramesh-tripathi.jpg",
    languages: ["Hindi", "Tamil", "Sanskrit"],
    experienceYears: 13,
    city: "Varanasi",
    bookingsCount: 1365,
    rating: 4.8,
    onlinePuja: true,
    faceToFacePuja: true,
    gender: "Male",
    age: 44,
    hometown: "Ayodhya, Uttar Pradesh",
    address: "Sigra, Varanasi",
    templeAvailability: "Flexible temple and home slots",
    callNumber: "+91-98717-82345",
    bio: "Trusted for Rudra jaap, Shiv puja and Mahamrityunjay anushthan with clear step-by-step ritual explanations."
  },
  {
    id: "pandit-9",
    slug: "pandit-gopal-krishna-shukla",
    name: "Pandit Gopal Krishna Shukla",
    image: "/images/pandits/gopal-krishna-shukla.jpg",
    languages: ["Hindi", "Kannada", "English"],
    experienceYears: 10,
    city: "Jaipur",
    bookingsCount: 1022,
    rating: 4.7,
    onlinePuja: false,
    faceToFacePuja: true,
    gender: "Male",
    age: 39,
    hometown: "Kanpur, Uttar Pradesh",
    address: "Malviya Nagar, Jaipur",
    templeAvailability: "Morning house-call puja preferred",
    callNumber: "+91-98718-92345",
    bio: "Conducts family-centric sanskar pujas, engagement and anniversary rituals with balanced traditional and practical approach."
  },
  {
    id: "pandit-10",
    slug: "acharya-mahesh-chaturvedi",
    name: "Acharya Mahesh Chaturvedi",
    image: "/images/pandits/mahesh-chaturvedi.jpg",
    languages: ["Hindi", "Marathi", "Bengali", "Sanskrit"],
    experienceYears: 24,
    city: "Delhi",
    bookingsCount: 2135,
    rating: 5.0,
    onlinePuja: true,
    faceToFacePuja: true,
    gender: "Male",
    age: 58,
    hometown: "Gwalior, Madhya Pradesh",
    address: "Karol Bagh, Delhi",
    templeAvailability: "Priority bookings for major festivals",
    callNumber: "+91-98719-02345",
    bio: "Veteran acharya for high-trust rituals, vastu shanti and special event pujas with deep scriptural clarity."
  }
];

export const panditFilterOptions = {
  languages: ["Hindi", "Marathi", "Gujarati", "Bengali", "English", "Telugu", "Tamil", "Kannada", "Sanskrit"],
  experience: [
    { label: "1+ years", value: "1" },
    { label: "5+ years", value: "5" },
    { label: "10+ years", value: "10" }
  ],
  cities: ["Noida", "Delhi", "Mathura", "Varanasi", "Jaipur"],
  pujaModes: [
    { label: "Online Puja", value: "online" },
    { label: "Face to Face Puja", value: "offline" }
  ]
};

export function getPandits() {
  return pandits;
}

export function getPanditBySlug(slug) {
  return pandits.find((pandit) => pandit.slug === slug) || null;
}
